### ISSUE TITLE
Check boxes are not persisted in search results

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#154]
### Issue
After Data Points have been searched for a list of valid results is displayed.  The user can tick the ones they want to add to their Request and then click on "With selected..." to add them. If the user clicks a couple of items and then clicks on the second page of results, then the page refreshes and the "With selected..." option is now disabled. Those selections have been lost.
### Solution
There are a couple of ways to solve this:
1. Prevent the user from moving to the second page if they have items ticked. Display a warning to the user saying that they have selected items and do they wish to add them to the request before moving on.
2. Remember the items that have been ticked on each page so that when the "With selected..." button is clicked they all get added. This is probably more complicated to achieve though.

**Comment by pjmonks** [comment]
I have seen this kind of issue multiple times in many web applications. At first, I was thinking how best to implement this, but then I was researching about UX for this scenario and it has made me think this might not be the best thing to do.

Links I've found for discussion:

- https://ux.stackexchange.com/questions/117564/for-web-pagination-and-multi-select-items-should-the-selection-be-persisted-acr
- https://ux.stackexchange.com/questions/43937/how-should-the-select-all-select-when-paginating-elements

If we think from the user's perspective, it's asking them to:

1. Select some items from page 1
2. Move to the next page
3. Select some more items from page 2
4. Perform an action, but _remember_ that you are combining page 1 and page 2 items.
5. Extrapolate this if you skip ahead to page 3, 4 etc.

Even with visual cues, it's basically asking the user to add mental load on them to remember what they've previously selected - did they remember to tick the right items on the previous page? How would they know now they are on page 2 and performing the action? How many pages of information must they keep in short term memory before they forget?

The points I've seen raised by others in the UX community suggest that a user should be able to see what they are performing an action on, to make it obvious. It may seem unfortunate that they cannot add 100 data points to a request at once, but at least they can be sure that the 20 they picked in one go are definitely assigned.

I think this needs some more discussion.

**Comment by NigelPalmer** [comment]
With the way the UI currently works there are some workflows that lead to a bad user experience.

1. A user has a list of fields. They tick the first one because they want it. They look at the second one and think "I want to know more", so click the "View Details" option. Having viewed that they have no option to return to the list other than clicking back. When they click back the user is returned to the fields list, but they no longer have any items ticked. This means they have to select the items they want again.

2. A user has 10 pages to navigate. They select a couple of items on the first page and then click on page 2. They select a couple more items, then click page 3, and so on until they get to page 10. They select two items then choose "With selected..." and create a new request. The request is created with only 2 items. At this point they realise they have to go through the whole process again to add the fields they want.

3. "Select all" is a little confusing. Does it "Select all" or "Select all items on this page"? It does all items on the page only, so I think it would be good to make this clear.

If we are going to stick with non persistence of the data then we do need to warn the user that they are about to lose information when they move off the page. This is particular clunky when viewing the details of a field.

Another alternative, which would require more thinking, is that the user is allowed to add as many fields as they want from any pages, but we present them with a list of what they have selected on every page. Possibly in a floating box that is always visible. This way they no longer have the mental load of "did I select the right thing", because the selections are visible.

Having said all that, I now have an idea of a simple(ish) solution that would improve the user experience:
1. Persist what has been ticked when the user clicks on "View Details".
2. When any field is ticked disable the search box, sort by, filters and page navigator controls. Display a message on the page saying something like "Selection(s) must be actioned". This would prevent the user from moving on an losing what they have selected. Then once nothing is ticked (which automatically happens after adding the items) all the controls reactivate. Clicking on menu items would cause the user to lose the selections but I think the user should expect that to happen.

Thoughts?

**Comment by NigelPalmer** [comment]
@pjmonks , any thoughts on my last comment above?

**Comment by pjmonks** [comment]
I'm not entirely sold on disabling controls when a selection is made, particular the search bar. Whatever change is made would need to make it very obvious what is happening at all times.

My gut feeling at the moment is to take a "wait and see" approach and get user feedback from real end-users. We could be thinking up complex UX scenarios when really no-one raises any issue with the existing feature set. If however real end-users do take issue with this, then it can be revisited.

**Comment by greg-at-occ** [comment]
Did we agree an action for this when we moved it to "Fix for next release", because if so, I can't work out what it was.

If we are still discussing: What user goal is the "With selected..." interaction designed to support? It seems to me that users _could_ get by with the '+' button on each search result, with the cost being that they must make _3nm_ clicks to add _n_ elements to _m_ requests, as opposed to _n + 3m_ using "With selected...". So from that I guess this feature is most useful when users want to add a lot of elements to a request, or when they want to add several elements to several requests.

If it's the former, and the user is only concerned with a single data request (might this be the vast majority of cases?) then it would be nice just to select my request in advance, and then have a single-click add for each element.

If it's the latter, perhaps an approach would be to add all the elements to a staging area and then commit that staging area to one or more requests. I tried to simulate this using Bookmarks (which don't seem to have pagination?) and it worked quite well.

**Comment by NigelPalmer** [comment]
I moved the task into "Fix for next release" to get it moving.

The Explorer doesn't work with the concept of selecting a Request and adding this to it. It took me a while to get my head around that model, since to me it could make more sense to create a request first and the add things to it.

Another addition to this screen that I am working on in another task is the ability to add all the class elements to an existing request from that page. We are then going to remove the ability to add a schema or a class to a request from the Browse page. So with that in mind, I think we should probably just remove the check boxes to simplify things.

Since there are many ideas flying around, I am going to consult with James as to the best way forwards.

**Comment by NigelPalmer** [comment]
James has responded with: 
"I think I best like the idea of a list of currently-selected items, but it definitely adds more complexity to the page. Having the ability to increase the page size might help here - having 50 / 100 / all items would at least allow the user to make large selections in a single go, rather than page-by-page."

Let's sit on this for today, and then we can make a firm plan of attack tomorrow.

**Comment by greg-at-occ** [comment]
Quick notes to start:

- Since the selection may span multiple pages, we will need to introduce a new UI component to show all the currently selected elements ("Current selection")
- The actions provided by "With selected..." should be moved and visually grouped into the "Current selection" component
- "Current selection" will ideally always be visible so users know how to action their selection (an improvement on the current UI where they must first find the "With selected..." button.
- The size of the selection could be large, so it should have a collapsed form (number of elements selects, and actions only) and expanded form (full paths of all selected elements, buttons to de-select individual elements)
- We should provide a button to clear the entire selection.
- The selection might persist between page loads (e.g. by use of LocalStorage) to avoid accidental loss of work.
- We might consider colour-coding or other visual linkage between the check boxes used for selection and the "Current selection" component.
- "Select all" should be renamed "Select entire page"
- It would improve usability to allow users to increase the page size as James suggests

**Comment by NigelPalmer** [comment]
@greg-at-occ , everything in your above comment makes sense to me. I am happy for you to run with it.

**Comment by greg-at-occ** [comment]
![image](https://user-images.githubusercontent.com/7668480/221566408-6578c25e-0f6e-4f32-be8b-1f3fba79cc0b.png)
![image](https://user-images.githubusercontent.com/7668480/221566429-22696855-3b3f-40cc-9793-ae12e2d4b7f3.png)

**Comment by greg-at-occ** [comment]
![image](https://user-images.githubusercontent.com/7668480/221566606-f32dd4b4-a3ac-4ad7-bbb3-0912bf945c14.png)
![image](https://user-images.githubusercontent.com/7668480/221566616-fa1383d7-d603-412d-9e32-4db26addf1cf.png)
