### ISSUE TITLE
Create new versions of Data Specifications

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#315]
# Description

Data Specifications, formerly known as Data Requests need to be versioned. When a data request is submitted the version number should be set. After it has been submitted, the user should be able to create a new version starting from the submitted one. We need to take advantage of Mauro's existing versioning functionality to do this.

In the Mdm-UI a user can finalise a data model (click on the green tick), at which point they get to choose the version number they wish to use. We need to use this same functionality in mdm-explorer, since a Data Specification is just a Data Model. We won't give the mdm-explorer user a choice though, mdm-explorer will simply set the "Major Version" number behind the scenes.

Once a data model is finalised in the Mdm-UI a user can create a new version by clicking on the "create a new version" button (2 docs in a pile, top right). This then asks the user to choose the type of version they wish to create, either fork, version or branch. For the Mdm Explorer we simply want to automatically select 'version' behind the scenes. The user should not be presented with a choice. Add a new button to the Data Specifications page that is only visible after a Data Specification has been submitted. When clicked it will create a new version.

If there are multiple versions with the same name, then only the most recent version should be displayed in the list of Data Specifications.

**Comment by CristianGimenez** [comment]
As mentioned during a call with Nigel, we are not implementing the finalisation of data specifications as part of this task since is going to be obsolete with the new sde anyway. 

So this task is now for:
- Listing only the latest data specification model version
- Having a controller to select diferent versions when viewing data spec details
- Create new versions of a finalised (submited) data specification

To implement these features I have created related tasks in the [researcher plugin](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/issues/34) and [mdm-resources](https://github.com/MauroDataMapper/mdm-resources/issues/106)
