### ISSUE TITLE
Template link - erroring

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#389]
# Description

When I click on Templates in the MDE I get an error. We need to find out what is going on and fix it. It may be a configuration issue, but if that is the case, then a useful error should be reported to help guide us to the solution. Similar to the messages we display when the MEQL query builder is not configured correctly. But we only need that IF this is a configuration error.

# Steps to reproduce

1. Click on 'Templates' - Error is immediately shown

# Expected behaviour

When you click on Templates, a list of Data Specification Templates should be shown to the user.

# Screenshots

![image](https://github.com/MauroDataMapper/mdm-explorer/assets/110250803/f989dd2c-89c6-4d82-b5af-5ab488f8abe3)

**Comment by giovannaOCC** [comment]
After a deep investigation on this...

Very first "Not Found" header might be misleading BUT if you read all the following message it says  BOTH TO:
- check the item really **exists**
- check user **has permission to view it**

Because of these information I logged to Mauro Admin to check if the users had permission to see Templates and they didn't.
Once permissions were granted, the user was able to login to MDM-Explorer and see the page without any issue.

- No changes are required - 
The message was exhaustive and the copy functionality would let user to eventually grab the details and send a message to the appropriate admin.
