### ISSUE TITLE
Elements already selected upon initial page load of dataclass details

### ISSUE THREAD

**Issue by abwilson23** [MauroDataMapper/mdm-explorer#417]
$${\color{red}Please \space read \space comments \space before \space commencing \space task}$$

# Description

After viewing the details of a dataclass from the Browse page I will occasionally notice that the 'Current selection' section of the page indicates that an element(s) has already been selected. If I look through all the elements listed on the page, I can find no such selected element(s). 

# Steps to reproduce

1. Go to 'Browse' page
2. Select a Schema and then a DataClass and click 'View Details' in the bottom right. 
3. Inspect the 'Current selection' box in the left column of the page and notice that it indicates an element(s) is selected even though you haven't interacted with any of the data elements on the page yet. 

# Expected behavior

The number of selected elements to be 0 upon initial page load. 

# Screenshots

![image](https://github.com/MauroDataMapper/mdm-explorer/assets/6440992/b8a4d377-ff72-4151-a134-ff04f4b7b8f4)

**Comment by NigelPalmer** [comment]
This is actually not as simple as it first seems. The reason that the selected elements are remembered is that there can be multiple pages of results. This has been designed so that a user can move through all the pages selecting what they want and then add all those elements in one go. This means that setting selecting elements on page load to zero will cause information to be lost.

Possible solutions.

1. Reset selected items when it **is not** a transition to another page in the field list for the same data.
2. Prevent the user from changing pages until they have added or discarded the items that they have selected.

**Comment by greg-at-occ** [comment]
Discussed with Nigel and agreed the selection should be cleared:

- When the selection is added to a data spec or used to create one
- 24 hours after it was last changed
